# Auto Generated by `python manage.py makemigrations`
# Generated by Django 5.2.11 on 2026-02-19 04:34
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('extra_col', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
